"""Integration tests for v0.7.6 Wave 4 — variant generator wiring into unit DB.

Verifies the TD-077 Wave 4 INTEGRATE of:
  - ``VehicleVariantGenerator`` (Sherman/Panzer/Halftrack/TD families)
  - ``FactionVariantGenerator`` (Commando/PIAT/Ranger/Fallschirmjäger etc)

into :func:`build_cc2_unit_database`. Follows the v0.7.5 squad_group_manager
integration-test pattern: exercise the wiring between generators, the unit
database, faction filters, and the deployment phase as a connected subsystem.

Pure generator unit tests live in ``tests/unit/test_variant_generators.py``.
"""

from __future__ import annotations

import logging

import pytest

from pycc2.domain.entities.unit import Faction
from pycc2.domain.systems.cc2_authentic_weapons import InfantryRole, VehicleType
from pycc2.domain.systems.deployment import (
    DeploymentConfig,
    DeploymentPhase,
    ZoneType,
)
from pycc2.domain.systems.unit_database import (
    build_cc2_unit_database,
    get_cc2_units,
    get_units_for_faction,
)
from pycc2.domain.systems.unit_templates import CC2UnitTemplate

# Sample IDs generated by VehicleVariantGenerator
_VEHICLE_VARIANT_IDS = [
    "us_sherman_easy_eight",
    "us_sherman_m4a3_75",
    "us_sherman_calliope",
    "de_panzer_iv_ausf_j",
    "de_panzer_iii_ausf_m",
    "de_sdkfz_251_16",
    "de_sdkfz_251_9",
    "us_m3_halftrack_75",
    "us_m36_jackson",
    "de_jagdpanzer_iv",
    "de_jagdpanther",
    "us_m8_greyhound",
    "de_sdkfz_234_puma",
    "uk_tetrarch",
]

# Sample IDs generated by FactionVariantGenerator
_FACTION_VARIANT_IDS = [
    "uk_commando_squad",
    "uk_piat_team_veteran",
    "uk_recce_troop",
    "us_ranger_squad_elite",
    "us_bazooka_team_veteran",
    "us_glider_infantry",
    "us_medic_team",
    "de_fallschirmjager_elite",
    "de_panzergrenadier_squad",
    "de_volksgrenadier_squad",
    "de_volksgrenadier_at",
    "de_medic_team",
    "pl_para_commando",
    "pl_para_scout",
    "pl_para_sniper",
    "pl_para_heavy_weapons",
]


@pytest.fixture(autouse=True)
def _reset_unit_cache():
    """Reset the lazy CC2_UNITS cache around each test (mirrors test_cc2_authentic_units)."""
    import pycc2.domain.systems.unit_database as db_module

    old_cache = db_module.CC2_UNITS
    db_module.CC2_UNITS = {}
    yield
    db_module.CC2_UNITS = old_cache


# ============================================================================
# Happy Path — generators are wired into build_cc2_unit_database()
# ============================================================================


class TestGeneratorsWiredIntoDatabase:
    """Both generators' output is reachable via the unit database."""

    def test_vehicle_variants_present_in_database(self):
        """All VehicleVariantGenerator template_ids are in build_cc2_unit_database()."""
        db = build_cc2_unit_database()
        missing = [tid for tid in _VEHICLE_VARIANT_IDS if tid not in db]
        assert missing == [], f"Missing vehicle variant IDs: {missing}"

    def test_faction_variants_present_in_database(self):
        """All FactionVariantGenerator template_ids are in build_cc2_unit_database()."""
        db = build_cc2_unit_database()
        missing = [tid for tid in _FACTION_VARIANT_IDS if tid not in db]
        assert missing == [], f"Missing faction variant IDs: {missing}"

    def test_database_grew_after_integration(self):
        """Database contains at least 30 more templates than the v0.7.5 baseline (>=80)."""
        db = build_cc2_unit_database()
        # v0.7.5 baseline was >=80; Wave 4 adds 30 variants (14 vehicle + 16 faction).
        assert len(db) >= 110, f"Expected >=110 templates after Wave 4 integration, got {len(db)}"


# ============================================================================
# Boundary — uniqueness and faction correctness
# ============================================================================


class TestUniquenessAndFaction:
    def test_all_template_ids_unique_in_database(self):
        """Every template_id in the database is unique (no duplicate keys)."""
        db = build_cc2_unit_database()
        # dict keys are inherently unique; this is a sanity check that the
        # conflict-skip logic in build_cc2_unit_database() did not silently
        # overwrite a factory entry with a generator entry.
        factory_ids = {
            "us_rifle_squad",
            "us_sherman_m4",
            "uk_firefly",
            "de_tiger_i",
            "pl_para_rifle_squad",
        }
        for fid in factory_ids:
            assert fid in db, f"Factory unit {fid} was overwritten/lost"

    def test_vehicle_variant_factions_correct(self):
        """Each vehicle variant's faction matches its ID prefix."""
        db = build_cc2_unit_database()
        expected_factions = {
            "us_sherman_easy_eight": Faction.AMERICAN,
            "us_sherman_m4a3_75": Faction.AMERICAN,
            "us_sherman_calliope": Faction.AMERICAN,
            "us_m36_jackson": Faction.AMERICAN,
            "us_m8_greyhound": Faction.AMERICAN,
            "us_m3_halftrack_75": Faction.AMERICAN,
            "de_panzer_iv_ausf_j": Faction.GERMAN,
            "de_panzer_iii_ausf_m": Faction.GERMAN,
            "de_sdkfz_251_16": Faction.GERMAN,
            "de_sdkfz_251_9": Faction.GERMAN,
            "de_jagdpanzer_iv": Faction.GERMAN,
            "de_jagdpanther": Faction.GERMAN,
            "de_sdkfz_234_puma": Faction.GERMAN,
            "uk_tetrarch": Faction.BRITISH,
        }
        for tid, expected_faction in expected_factions.items():
            assert db[tid].faction == expected_faction, (
                f"{tid}: expected {expected_faction.name}, got {db[tid].faction.name}"
            )

    def test_faction_variant_factions_correct(self):
        """Each faction variant's faction matches its ID prefix."""
        db = build_cc2_unit_database()
        expected_factions = {
            "uk_commando_squad": Faction.BRITISH,
            "uk_piat_team_veteran": Faction.BRITISH,
            "uk_recce_troop": Faction.BRITISH,
            "us_ranger_squad_elite": Faction.AMERICAN,
            "us_bazooka_team_veteran": Faction.AMERICAN,
            "us_glider_infantry": Faction.AMERICAN,
            "us_medic_team": Faction.AMERICAN,
            "de_fallschirmjager_elite": Faction.GERMAN,
            "de_panzergrenadier_squad": Faction.GERMAN,
            "de_volksgrenadier_squad": Faction.GERMAN,
            "de_volksgrenadier_at": Faction.GERMAN,
            "de_medic_team": Faction.GERMAN,
            "pl_para_commando": Faction.POLISH,
            "pl_para_scout": Faction.POLISH,
            "pl_para_sniper": Faction.POLISH,
            "pl_para_heavy_weapons": Faction.POLISH,
        }
        for tid, expected_faction in expected_factions.items():
            assert db[tid].faction == expected_faction, (
                f"{tid}: expected {expected_faction.name}, got {db[tid].faction.name}"
            )


# ============================================================================
# Integration — faction filters + deployment phase consume new templates
# ============================================================================


class TestFactionFilterAndDeployment:
    def test_get_units_for_faction_includes_new_variants(self):
        """get_units_for_faction() returns the new variants alongside factory units."""
        db = build_cc2_unit_database()
        for faction in Faction:
            faction_units = get_units_for_faction(faction)
            # Every returned unit must belong to the requested faction.
            assert all(u.faction == faction for u in faction_units)
            assert len(faction_units) < len(db)

        # Spot-check: US faction now includes the Easy Eight + Ranger Elite.
        us_units = get_units_for_faction(Faction.AMERICAN)
        us_ids = {u.template_id for u in us_units}
        assert "us_sherman_easy_eight" in us_ids
        assert "us_ranger_squad_elite" in us_ids
        # And the factory unit is still there.
        assert "us_rifle_squad" in us_ids

        # Spot-check: Polish faction gained 4 new para variants.
        pl_units = get_units_for_faction(Faction.POLISH)
        pl_new = {u.template_id for u in pl_units} & {
            "pl_para_commando",
            "pl_para_scout",
            "pl_para_sniper",
            "pl_para_heavy_weapons",
        }
        assert len(pl_new) == 4

    def test_get_cc2_units_lazy_cache_contains_new_variants(self):
        """The lazy cache returned by get_cc2_units() also exposes the new variants."""
        db = get_cc2_units()
        assert "us_sherman_easy_eight" in db
        assert "uk_commando_squad" in db
        assert "de_jagdpanther" in db
        assert "pl_para_sniper" in db
        # Second call returns the same cached object.
        assert get_cc2_units() is db

    def test_deployment_place_unit_accepts_new_vehicle_variant(self):
        """DeploymentPhase.place_unit() succeeds for a new vehicle variant ID."""
        config = DeploymentConfig(
            map_width=3,
            map_height=3,
            ally_zones=[[ZoneType.FRIENDLY for _ in range(3)] for _ in range(3)],
            axis_zones=[[ZoneType.FRIENDLY for _ in range(3)] for _ in range(3)],
            max_infantry=9,
            max_support=6,
            max_total=15,
        )
        phase = DeploymentPhase(config)
        phase.start_deployment(Faction.AMERICAN)

        # us_sherman_easy_eight is a TANK_MEDIUM (support slot) — should place.
        assert phase.place_unit("us_sherman_easy_eight", 0, 0) is True
        deployed = phase.get_deployed_positions(Faction.AMERICAN)
        assert deployed == [(0, 0, "us_sherman_easy_eight")]

    def test_deployment_place_unit_accepts_new_infantry_variant(self):
        """DeploymentPhase.place_unit() succeeds for a new faction variant ID."""
        config = DeploymentConfig(
            map_width=3,
            map_height=3,
            ally_zones=[[ZoneType.FRIENDLY for _ in range(3)] for _ in range(3)],
            axis_zones=[[ZoneType.FRIENDLY for _ in range(3)] for _ in range(3)],
            max_infantry=9,
            max_support=6,
            max_total=15,
        )
        phase = DeploymentPhase(config)
        phase.start_deployment(Faction.BRITISH)

        # uk_commando_squad is HEAVY_ASSAULT (infantry slot) — should place.
        assert phase.place_unit("uk_commando_squad", 1, 0) is True
        deployed = phase.get_deployed_positions(Faction.BRITISH)
        assert deployed == [(1, 0, "uk_commando_squad")]

    def test_deployment_rejects_unknown_template_id(self):
        """DeploymentPhase.place_unit() returns False for an unknown template_id."""
        config = DeploymentConfig(
            map_width=3,
            map_height=3,
            ally_zones=[[ZoneType.FRIENDLY for _ in range(3)] for _ in range(3)],
            axis_zones=[[ZoneType.FRIENDLY for _ in range(3)] for _ in range(3)],
        )
        phase = DeploymentPhase(config)
        phase.start_deployment(Faction.AMERICAN)
        assert phase.place_unit("nonexistent_template_xyz", 0, 0) is False


# ============================================================================
# Conflict handling — duplicate IDs are skipped with a warning log
# ============================================================================


class TestConflictHandling:
    """When a generator yields a template_id that already exists, it is skipped."""

    def test_duplicate_id_skipped_with_warning_log(self, caplog):
        """A generator-produced ID colliding with a factory entry is skipped + logged."""
        from pycc2.domain.systems import unit_database as db_module
        from pycc2.domain.systems.faction_variant_generator import (
            FactionVariantGenerator,
        )

        # Build a factory-only database (no generators yet) and inject one
        # duplicate ID so we can observe the skip behaviour deterministically.
        factory_db = build_cc2_unit_database()
        # Sanity: the ID we will duplicate must NOT already be a factory entry.
        assert "uk_commando_squad" in factory_db  # added by generator
        # Reset cache and rebuild, then tamper: pre-seed the dict with a
        # colliding entry before the generator runs. We simulate this by
        # monkey-patching FactionVariantGenerator.generate to yield a template
        # whose ID already exists in the factory database.
        colliding_template = CC2UnitTemplate(
            template_id="us_rifle_squad",  # existing factory ID
            display_name="Duplicate Rifle Squad",
            faction=Faction.AMERICAN,
            role=InfantryRole.RIFLE,
            weapon_primary_id="us_m1_garand",
        )
        original_generate = FactionVariantGenerator.generate

        def _patched_generate(self):
            # Return a list with one colliding + one unique template.
            return [
                colliding_template,
                CC2UnitTemplate(
                    template_id="test_unique_faction_variant",
                    display_name="Unique Test Variant",
                    faction=Faction.AMERICAN,
                    role=InfantryRole.RIFLE,
                    weapon_primary_id="us_m1_garand",
                ),
            ]

        FactionVariantGenerator.generate = _patched_generate  # type: ignore[method-assign]
        try:
            db_module.CC2_UNITS = {}
            with caplog.at_level(logging.WARNING, logger="pycc2.domain.systems.unit_database"):
                db = build_cc2_unit_database()
            # The colliding ID must still point at the FACTORY template,
            # not the duplicate.
            assert db["us_rifle_squad"].display_name != "Duplicate Rifle Squad"
            # The unique test variant was added.
            assert "test_unique_faction_variant" in db
            # A warning was logged for the collision.
            warning_messages = [r.message for r in caplog.records if r.levelno == logging.WARNING]
            assert any("Template ID conflict: us_rifle_squad" in msg for msg in warning_messages), (
                f"Expected conflict warning, got: {warning_messages}"
            )
        finally:
            FactionVariantGenerator.generate = original_generate  # type: ignore[method-assign]


# ============================================================================
# Role correctness — variants are queryable via get_units_by_role
# ============================================================================


class TestRoleQuery:
    def test_new_tank_destroyer_variants_queryable_by_role(self):
        """get_units_by_role(TANK_DESTROYER) includes the new TD variants."""
        from pycc2.domain.systems.unit_database import get_units_by_role

        build_cc2_unit_database()  # populate cache
        td_units = get_units_by_role(VehicleType.TANK_DESTROYER)
        td_ids = {u.template_id for u in td_units}
        assert "us_m36_jackson" in td_ids
        assert "de_jagdpanzer_iv" in td_ids
        assert "de_jagdpanther" in td_ids

    def test_new_heavy_assault_variants_queryable_by_role(self):
        """get_units_by_role(HEAVY_ASSAULT) includes the new elite squads."""
        from pycc2.domain.systems.unit_database import get_units_by_role

        build_cc2_unit_database()
        ha_units = get_units_by_role(InfantryRole.HEAVY_ASSAULT)
        ha_ids = {u.template_id for u in ha_units}
        assert "uk_commando_squad" in ha_ids
        assert "us_ranger_squad_elite" in ha_ids
        assert "de_panzergrenadier_squad" in ha_ids
