from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ISoundSystem(Protocol):
    def play_shot(self, weapon_type: str = "rifle") -> None: ...
    def play_hit(self, is_critical: bool = False) -> None: ...
    def play_death(self) -> None: ...
    def play_footstep(self, terrain: str = "grass") -> None: ...
    def play_sound_with_distance(self, sound_id: str, source_pos: Any, camera_pos: Any, max_distance: float = 500.0) -> None: ...
