"""Vehicle weapon profiles — tank guns, coaxial MGs, vehicle-mounted weapons (P5-1 batch 1).

Extracted from cc2_authentic_weapons.py. Builds the vehicle portion of the
CC2 weapon database (Light/Medium/Heavy Tank Guns, Vehicle MGs, Mortars,
Snipers, special weapons).
"""

from __future__ import annotations

from pycc2.domain.entities.unit import Faction
from pycc2.domain.systems.weapon_type_defs import WeaponProfile, WeaponType


def build_vehicle_weapons() -> dict[str, WeaponProfile]:
    """Build vehicle-mounted weapon profiles (tank guns, MGs, specials)."""
    weapons: dict[str, WeaponProfile] = {}
    # ================================================================
    # VEHICLE WEAPONS (Tank Guns, Coaxial MGs)
    # ================================================================

    # --- Light Tank Guns ---
    weapons["m3_37mm"] = WeaponProfile(
        id="m3_37mm",
        name="M3 37mm",
        weapon_type=WeaponType.TANK_CANNON_LIGHT,
        users=[Faction.AMERICAN],
        range_short=3,
        range_medium=6,
        range_long=9,
        range_max=12,
        accuracy_short=0.55,
        accuracy_medium=0.40,
        damage_vs_light_armor=45,
        damage_vs_heavy_armor=12,
        rpm=25,
        suppress_power=0.35,
        year_introduced=1940,
        notes="Stuart light tank gun",
    )

    weapons["kwk36_37mm"] = WeaponProfile(
        id="kwk36_37mm",
        name="3.7cm KwK 36",
        weapon_type=WeaponType.TANK_CANNON_LIGHT,
        users=[Faction.GERMAN],
        range_short=3,
        range_medium=6,
        range_long=9,
        range_max=12,
        accuracy_short=0.58,
        accuracy_medium=0.42,
        damage_vs_light_armor=48,
        damage_vs_heavy_armor=14,
        rpm=25,
        suppress_power=0.38,
        year_introduced=1936,
        notes="PzKpfw II / early PzKpfw III gun",
    )

    # --- Medium Tank Guns ---
    weapons["m3_75mm_m4"] = WeaponProfile(
        id="m3_75mm_m4",
        name="M3 75mm (M4 Sherman)",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.AMERICAN],
        range_short=4,
        range_medium=8,
        range_long=12,
        range_max=15,
        accuracy_short=0.62,
        accuracy_medium=0.48,
        damage_vs_light_armor=55,
        damage_vs_heavy_armor=22,
        rpm=18,
        suppress_power=0.48,
        year_introduced=1941,
        notes="Sherman main gun, adequate vs PzIV, weak vs Panther/Tiger",
    )

    weapons["kwk40_75mm"] = WeaponProfile(
        id="kwk40_75mm",
        name="7.5cm KwK 40 L/48",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.GERMAN],
        range_short=5,
        range_medium=9,
        range_long=14,
        range_max=17,
        accuracy_short=0.68,
        accuracy_medium=0.54,
        damage_vs_light_armor=62,
        damage_vs_heavy_armor=28,
        rpm=15,
        suppress_power=0.55,
        year_introduced=1942,
        notes="Panzer IV F/G/H main gun, excellent all-around",
    )

    weapons["qv_75mm"] = WeaponProfile(
        id="qv_75mm",
        name="QF 75mm (Cromwell/Churchill)",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.BRITISH],
        range_short=4,
        range_medium=8,
        range_long=12,
        range_max=15,
        accuracy_short=0.60,
        accuracy_medium=0.46,
        damage_vs_light_armor=52,
        damage_vs_heavy_armor=20,
        rpm=16,
        suppress_power=0.45,
        year_introduced=1942,
        notes="British 75mm, similar performance to US 75mm",
    )

    # --- Heavy Tank Guns ---
    weapons["kwk36_88mm"] = WeaponProfile(
        id="kwk36_88mm",
        name="8.8cm KwK 36 L/56",
        weapon_type=WeaponType.TANK_CANNON_HEAVY,
        users=[Faction.GERMAN],
        range_short=6,
        range_medium=12,
        range_long=18,
        range_max=24,
        accuracy_short=0.78,
        accuracy_medium=0.64,
        damage_vs_light_armor=85,
        damage_vs_heavy_armor=55,
        rpm=10,
        suppress_power=0.72,
        year_introduced=1940,
        notes="Tiger I main gun, devastating at all ranges",
    )

    weapons["kwk42_75mm"] = WeaponProfile(
        id="kwk42_75mm",
        name="7.5cm KwK 42 L/70",
        weapon_type=WeaponType.TANK_CANNON_HEAVY,
        users=[Faction.GERMAN],
        range_short=6,
        range_medium=12,
        range_long=18,
        range_max=24,
        accuracy_short=0.76,
        accuracy_medium=0.62,
        damage_vs_light_armor=80,
        damage_vs_heavy_armor=50,
        rpm=12,
        suppress_power=0.68,
        year_introduced=1943,
        notes="Panther main gun, excellent penetration",
    )

    weapons["qf_17pdr"] = WeaponProfile(
        id="qf_17pdr",
        name="QF 17-pounder (Firefly)",
        weapon_type=WeaponType.TANK_CANNON_HEAVY,
        users=[Faction.BRITISH],
        range_short=6,
        range_medium=12,
        range_long=18,
        range_max=24,
        accuracy_short=0.74,
        accuracy_medium=0.60,
        damage_vs_light_armor=78,
        damage_vs_heavy_armor=48,
        rpm=10,
        suppress_power=0.65,
        year_introduced=1943,
        notes="Sherman Firefly conversion, best allied AT gun",
    )

    weapons["qv_95mm"] = WeaponProfile(
        id="qv_95mm",
        name="QF 95mm howitzer",
        weapon_type=WeaponType.TANK_CANNON_HEAVY,
        users=[Faction.BRITISH],
        range_short=4,
        range_medium=8,
        range_long=14,
        range_max=18,
        accuracy_short=0.52,
        accuracy_medium=0.38,
        damage_vs_light_armor=65,
        damage_vs_heavy_armor=35,
        area_effect=True,
        splash_radius=2,
        rpm=8,
        suppress_power=0.60,
        year_introduced=1942,
        notes="Churchill CS (Close Support) howitzer, HE rounds",
    )

    # --- Vehicle MGs (Coaxial / Hull) ---
    weapons["coax_30cal"] = WeaponProfile(
        id="coax_30cal",
        name=".30 Cal Coaxial M1919A4",
        weapon_type=WeaponType.VEHICLE_MOUNTED_MG,
        users=[Faction.AMERICAN],
        range_short=4,
        range_medium=7,
        range_long=10,
        range_max=12,
        accuracy_short=0.55,
        damage_vs_infantry=35,
        rpm=500,
        suppress_power=0.50,
        year_introduced=1943,
    )

    weapons["coax_mg34"] = WeaponProfile(
        id="coax_mg34",
        name="Coaxial MG34",
        weapon_type=WeaponType.VEHICLE_MOUNTED_MG,
        users=[Faction.GERMAN],
        range_short=5,
        range_medium=8,
        range_long=12,
        range_max=14,
        accuracy_short=0.58,
        damage_vs_infantry=38,
        rpm=800,
        suppress_power=0.55,
        year_introduced=1938,
    )

    weapons["coax_besa"] = WeaponProfile(
        id="coax_besa",
        name="Coaxial Besa 7.92mm",
        weapon_type=WeaponType.VEHICLE_MOUNTED_MG,
        users=[Faction.BRITISH],
        range_short=5,
        range_medium=8,
        range_long=12,
        range_max=14,
        accuracy_short=0.56,
        damage_vs_infantry=36,
        rpm=500,
        suppress_power=0.48,
        year_introduced=1939,
    )

    # ================================================================
    # ANTI-TANK GUNS (Fixed AT artillery)
    # ================================================================

    weapons["uk_6pdr"] = WeaponProfile(
        id="uk_6pdr",
        name="Ordnance QF 6-pounder",
        weapon_type=WeaponType.ANTI_TANK_GUN,
        users=[Faction.BRITISH],
        range_short=4,
        range_medium=10,
        range_long=16,
        range_max=20,
        accuracy_short=0.72,
        accuracy_medium=0.58,
        accuracy_long=0.35,
        damage_vs_infantry=35.0,
        damage_vs_light_armor=70.0,
        damage_vs_heavy_armor=45.0,
        rpm=15,
        burst_size=1,
        suppress_power=0.40,
        can_penetrate=True,
        ammo_capacity=50,
        year_introduced=1942,
        notes="British 57mm AT gun, effective vs PzIV",
    )

    weapons["de_pak40"] = WeaponProfile(
        id="de_pak40",
        name="7.5cm Pak 40",
        weapon_type=WeaponType.ANTI_TANK_GUN,
        users=[Faction.GERMAN],
        range_short=5,
        range_medium=12,
        range_long=18,
        range_max=24,
        accuracy_short=0.78,
        accuracy_medium=0.65,
        accuracy_long=0.42,
        damage_vs_infantry=40.0,
        damage_vs_light_armor=85.0,
        damage_vs_heavy_armor=65.0,
        rpm=14,
        burst_size=1,
        suppress_power=0.50,
        can_penetrate=True,
        ammo_capacity=40,
        year_introduced=1942,
        notes="German 75mm AT gun, devastating vs all Allied armor",
    )

    weapons["us_m1_57mm"] = WeaponProfile(
        id="us_m1_57mm",
        name="M1 57mm AT Gun",
        weapon_type=WeaponType.ANTI_TANK_GUN,
        users=[Faction.AMERICAN],
        range_short=4,
        range_medium=10,
        range_long=16,
        range_max=20,
        accuracy_short=0.70,
        accuracy_medium=0.55,
        accuracy_long=0.33,
        damage_vs_infantry=33.0,
        damage_vs_light_armor=68.0,
        damage_vs_heavy_armor=42.0,
        rpm=15,
        burst_size=1,
        suppress_power=0.38,
        can_penetrate=True,
        ammo_capacity=50,
        year_introduced=1943,
        notes="US copy of 6-pounder, slightly lower quality",
    )

    # ================================================================
    # EXPANDED ROSTER WEAPONS
    # ================================================================

    # --- German MG34 LMG variant (lighter bipod) ---
    weapons["de_mg34_lmg"] = WeaponProfile(
        id="de_mg34_lmg",
        name="MG34 (LMG)",
        weapon_type=WeaponType.MACHINE_GUN_LIGHT,
        users=[Faction.GERMAN],
        range_short=3,
        range_medium=8,
        range_long=12,
        range_max=15,
        accuracy_short=0.65,
        accuracy_medium=0.50,
        accuracy_long=0.30,
        damage_vs_infantry=25.0,
        damage_vs_light_armor=8.0,
        damage_vs_heavy_armor=2.0,
        rpm=900,
        burst_size=5,
        suppress_power=0.55,
        can_penetrate=False,
        ammo_capacity=75,
        year_introduced=1934,
        notes="MG34 lighter bipod LMG variant, more mobile but less stable",
    )

    # --- German 81mm Mortar (GrW 34) ---
    weapons["de_81mm_mortar"] = WeaponProfile(
        id="de_81mm_mortar",
        name="8.1cm GrW 34",
        weapon_type=WeaponType.MORTAR_HEAVY,
        users=[Faction.GERMAN],
        range_short=4,
        range_medium=11,
        range_long=17,
        range_max=22,
        accuracy_short=0.62,
        accuracy_medium=0.48,
        accuracy_long=0.28,
        damage_vs_infantry=52.0,
        damage_vs_light_armor=18.0,
        damage_vs_heavy_armor=4.0,
        rpm=7,
        burst_size=1,
        suppress_power=0.68,
        can_penetrate=False,
        area_effect=True,
        splash_radius=3,
        ammo_capacity=30,
        year_introduced=1934,
        notes="Standard German 81mm mortar, battalion-level indirect fire",
    )

    # --- US 60mm Mortar ---
    weapons["us_60mm_mortar"] = WeaponProfile(
        id="us_60mm_mortar",
        name="M2 60mm Mortar",
        weapon_type=WeaponType.MORTAR_LIGHT,
        users=[Faction.AMERICAN],
        range_short=3,
        range_medium=7,
        range_long=12,
        range_max=15,
        accuracy_short=0.58,
        accuracy_medium=0.42,
        accuracy_long=0.22,
        damage_vs_infantry=40.0,
        damage_vs_light_armor=10.0,
        damage_vs_heavy_armor=2.0,
        rpm=8,
        burst_size=1,
        suppress_power=0.50,
        can_penetrate=False,
        area_effect=True,
        splash_radius=2,
        ammo_capacity=30,
        year_introduced=1940,
        notes="US light company-level mortar",
    )

    # --- Panzerfaust 60 ---
    weapons["de_panzerfaust60"] = WeaponProfile(
        id="de_panzerfaust60",
        name="Panzerfaust 60",
        weapon_type=WeaponType.ANTI_TANK_ROCKET,
        users=[Faction.GERMAN],
        range_short=1,
        range_medium=3,
        range_long=0,
        range_max=3,
        accuracy_short=0.75,
        accuracy_medium=0.40,
        accuracy_long=0.0,
        damage_vs_infantry=30.0,
        damage_vs_light_armor=90.0,
        damage_vs_heavy_armor=80.0,
        rpm=1,
        burst_size=1,
        suppress_power=0.30,
        can_penetrate=True,
        ammo_capacity=1,
        year_introduced=1943,
        notes="Improved Panzerfaust with 60m range, disposable AT weapon",
    )

    # --- British Officer's STEN ---
    weapons["uk_officer_sten"] = WeaponProfile(
        id="uk_officer_sten",
        name="STEN Mk.V (Officer)",
        weapon_type=WeaponType.SUBMACHINE_GUN,
        users=[Faction.BRITISH, Faction.POLISH],
        range_short=2,
        range_medium=4,
        range_long=0,
        range_max=5,
        accuracy_short=0.55,
        accuracy_medium=0.30,
        accuracy_long=0.0,
        damage_vs_infantry=12.0,
        damage_vs_light_armor=2.0,
        damage_vs_heavy_armor=0.5,
        rpm=540,
        burst_size=3,
        suppress_power=0.15,
        can_penetrate=False,
        ammo_capacity=32,
        year_introduced=1944,
        notes="Officer variant of STEN Mk.V, compact personal defense weapon",
    )

    # --- German Luger P08 ---
    weapons["de_officer_p08"] = WeaponProfile(
        id="de_officer_p08",
        name="Luger P08",
        weapon_type=WeaponType.PISTOL,
        users=[Faction.GERMAN],
        range_short=1,
        range_medium=2,
        range_long=0,
        range_max=3,
        accuracy_short=0.70,
        accuracy_medium=0.35,
        accuracy_long=0.0,
        damage_vs_infantry=8.0,
        damage_vs_light_armor=1.0,
        damage_vs_heavy_armor=0.0,
        rpm=30,
        burst_size=1,
        suppress_power=0.05,
        can_penetrate=False,
        ammo_capacity=8,
        year_introduced=1908,
        notes="Iconic German officer pistol, 9mm Parabellum",
    )

    # --- FG42 Fallschirmjägergewehr ---
    weapons["de_fg42"] = WeaponProfile(
        id="de_fg42",
        name="FG 42",
        weapon_type=WeaponType.RIFLE,
        users=[Faction.GERMAN],
        range_short=4,
        range_medium=7,
        range_long=10,
        range_max=12,
        accuracy_short=0.62,
        accuracy_medium=0.45,
        accuracy_long=0.25,
        damage_vs_infantry=35.0,
        damage_vs_light_armor=8.0,
        damage_vs_heavy_armor=1.0,
        rpm=750,
        burst_size=10,
        suppress_power=0.35,
        ammo_capacity=120,
        year_introduced=1942,
        notes="Fallschirmjäger automatic rifle, selective-fire, rare and prized",
    )

    # --- 7.5cm KwK 40 (Panzer IV mount) ---
    weapons["de_75mm_kwk40"] = WeaponProfile(
        id="de_75mm_kwk40",
        name="7.5cm KwK 40 L/48",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.GERMAN],
        range_short=5,
        range_medium=9,
        range_long=14,
        range_max=17,
        accuracy_short=0.68,
        accuracy_medium=0.54,
        accuracy_long=0.30,
        damage_vs_infantry=40.0,
        damage_vs_light_armor=62.0,
        damage_vs_heavy_armor=28.0,
        rpm=15,
        burst_size=1,
        suppress_power=0.55,
        can_penetrate=True,
        ammo_capacity=50,
        year_introduced=1942,
        notes="Panzer IV main gun, excellent all-around performance",
    )

    # --- 7.5cm StuK 40 (StuG III mount) ---
    weapons["de_75mm_stug"] = WeaponProfile(
        id="de_75mm_stug",
        name="7.5cm StuK 40 L/48",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.GERMAN],
        range_short=5,
        range_medium=9,
        range_long=14,
        range_max=17,
        accuracy_short=0.66,
        accuracy_medium=0.52,
        accuracy_long=0.28,
        damage_vs_infantry=38.0,
        damage_vs_light_armor=60.0,
        damage_vs_heavy_armor=26.0,
        rpm=15,
        burst_size=1,
        suppress_power=0.52,
        can_penetrate=True,
        ammo_capacity=44,
        year_introduced=1942,
        notes="StuG III assault gun main weapon, low profile ambush gun",
    )

    # --- 15cm sFH 18/1 (Hummel SPG) ---
    weapons["de_150mm_hummel"] = WeaponProfile(
        id="de_150mm_hummel",
        name="15cm sFH 18/1 (Hummel)",
        weapon_type=WeaponType.TANK_CANNON_HEAVY,
        users=[Faction.GERMAN],
        range_short=4,
        range_medium=10,
        range_long=18,
        range_max=24,
        accuracy_short=0.45,
        accuracy_medium=0.30,
        accuracy_long=0.15,
        damage_vs_infantry=85.0,
        damage_vs_light_armor=70.0,
        damage_vs_heavy_armor=45.0,
        rpm=4,
        burst_size=1,
        suppress_power=0.80,
        can_penetrate=True,
        area_effect=True,
        splash_radius=3,
        ammo_capacity=18,
        year_introduced=1943,
        notes="Hummel SPG 150mm howitzer, devastating HE, open-topped",
    )

    # --- QF 75mm (Cromwell mount) ---
    weapons["uk_75mm_cromwell"] = WeaponProfile(
        id="uk_75mm_cromwell",
        name="QF 75mm (Cromwell)",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.BRITISH],
        range_short=4,
        range_medium=8,
        range_long=12,
        range_max=15,
        accuracy_short=0.60,
        accuracy_medium=0.46,
        accuracy_long=0.25,
        damage_vs_infantry=35.0,
        damage_vs_light_armor=52.0,
        damage_vs_heavy_armor=20.0,
        rpm=16,
        burst_size=1,
        suppress_power=0.45,
        can_penetrate=True,
        ammo_capacity=50,
        year_introduced=1942,
        notes="Cromwell tank main gun, similar to US 75mm",
    )

    # --- 76mm M1A1 (Sherman 76mm) ---
    weapons["us_76mm_sherman"] = WeaponProfile(
        id="us_76mm_sherman",
        name="76mm M1A1 (Sherman)",
        weapon_type=WeaponType.TANK_CANNON_MEDIUM,
        users=[Faction.AMERICAN],
        range_short=5,
        range_medium=10,
        range_long=15,
        range_max=18,
        accuracy_short=0.66,
        accuracy_medium=0.52,
        accuracy_long=0.30,
        damage_vs_infantry=38.0,
        damage_vs_light_armor=65.0,
        damage_vs_heavy_armor=35.0,
        rpm=14,
        burst_size=1,
        suppress_power=0.52,
        can_penetrate=True,
        ammo_capacity=45,
        year_introduced=1944,
        notes="Improved Sherman gun, better AT performance than 75mm",
    )

    # --- M2HB .50 Cal HMG ---
    weapons["us_m2hb_50cal"] = WeaponProfile(
        id="us_m2hb_50cal",
        name="M2HB .50 Cal",
        weapon_type=WeaponType.VEHICLE_MOUNTED_MG,
        users=[Faction.AMERICAN],
        range_short=5,
        range_medium=9,
        range_long=14,
        range_max=18,
        accuracy_short=0.58,
        accuracy_medium=0.42,
        accuracy_long=0.22,
        damage_vs_infantry=45.0,
        damage_vs_light_armor=20.0,
        damage_vs_heavy_armor=5.0,
        rpm=575,
        burst_size=10,
        suppress_power=0.60,
        can_penetrate=True,
        ammo_capacity=200,
        year_introduced=1933,
        notes="Heavy .50 cal MG, devastating vs infantry and light vehicles",
    )

    # --- Browning BAR M1918A2 ---
    weapons["us_browning_bar"] = WeaponProfile(
        id="us_browning_bar",
        name="Browning BAR M1918A2",
        weapon_type=WeaponType.MACHINE_GUN_LIGHT,
        users=[Faction.AMERICAN],
        range_short=3,
        range_medium=6,
        range_long=9,
        range_max=11,
        accuracy_short=0.60,
        accuracy_medium=0.45,
        accuracy_long=0.25,
        damage_vs_infantry=32.0,
        damage_vs_light_armor=8.0,
        damage_vs_heavy_armor=1.0,
        rpm=450,
        burst_size=5,
        suppress_power=0.35,
        ammo_capacity=80,
        year_introduced=1940,
        notes="Automatic rifle, squad-level support weapon, 20-round magazine",
    )

    # --- Kar98k Sniper Variant ---
    weapons["de_kar98k_sniper"] = WeaponProfile(
        id="de_kar98k_sniper",
        name="Kar98k (ZF39)",
        weapon_type=WeaponType.SNIPER_RIFLE,
        users=[Faction.GERMAN],
        range_short=6,
        range_medium=10,
        range_long=14,
        range_max=18,
        accuracy_short=0.85,
        accuracy_medium=0.70,
        accuracy_long=0.48,
        damage_vs_infantry=45.0,
        damage_vs_light_armor=12.0,
        damage_vs_heavy_armor=1.0,
        rpm=12,
        burst_size=1,
        suppress_power=0.08,
        ammo_capacity=30,
        year_introduced=1939,
        notes="Scoped Kar98k sniper rifle, ZF39 4x scope",
    )

    # --- Lee-Enfield No.4 Sniper ---
    weapons["uk_sniper_no4"] = WeaponProfile(
        id="uk_sniper_no4",
        name="Lee-Enfield No.4 (T)",
        weapon_type=WeaponType.SNIPER_RIFLE,
        users=[Faction.BRITISH, Faction.POLISH],
        range_short=6,
        range_medium=10,
        range_long=14,
        range_max=18,
        accuracy_short=0.84,
        accuracy_medium=0.68,
        accuracy_long=0.46,
        damage_vs_infantry=44.0,
        damage_vs_light_armor=11.0,
        damage_vs_heavy_armor=1.0,
        rpm=12,
        burst_size=1,
        suppress_power=0.08,
        ammo_capacity=30,
        year_introduced=1942,
        notes="Scoped Lee-Enfield No.4(T), No.32 3.5x scope",
    )

    # --- Lee-Enfield No.4 (para variant) ---
    weapons["uk_enfield_no4"] = WeaponProfile(
        id="uk_enfield_no4",
        name="Lee-Enfield No.4",
        weapon_type=WeaponType.RIFLE,
        users=[Faction.BRITISH, Faction.POLISH],
        range_short=5,
        range_medium=8,
        range_long=11,
        range_max=13,
        accuracy_short=0.76,
        accuracy_medium=0.60,
        accuracy_long=0.35,
        damage_vs_infantry=40.0,
        damage_vs_light_armor=9.0,
        damage_vs_heavy_armor=1.0,
        rpm=25,
        burst_size=10,
        suppress_power=0.20,
        ammo_capacity=50,
        year_introduced=1941,
        notes="Standard Lee-Enfield No.4, British and Polish airborne issue",
    )

    # --- Browning .30 Cal M1919A4 (infantry squad variant) ---
    weapons["us_browning_30cal"] = WeaponProfile(
        id="us_browning_30cal",
        name="Browning .30 Cal M1919A4",
        weapon_type=WeaponType.MACHINE_GUN_HEAVY,
        users=[Faction.AMERICAN],
        range_short=5,
        range_medium=8,
        range_long=12,
        range_max=14,
        accuracy_short=0.66,
        accuracy_medium=0.50,
        accuracy_long=0.28,
        damage_vs_infantry=42.0,
        damage_vs_light_armor=14.0,
        damage_vs_heavy_armor=2.0,
        rpm=500,
        burst_size=20,
        suppress_power=0.60,
        ammo_capacity=250,
        year_introduced=1943,
        notes="Browning .30 cal machine gun, infantry squad variant",
    )

    # --- MG34 Vehicle Mount ---
    weapons["de_mg34_vehicle"] = WeaponProfile(
        id="de_mg34_vehicle",
        name="MG34 (Vehicle Mount)",
        weapon_type=WeaponType.VEHICLE_MOUNTED_MG,
        users=[Faction.GERMAN],
        range_short=4,
        range_medium=8,
        range_long=12,
        range_max=14,
        accuracy_short=0.58,
        accuracy_medium=0.44,
        accuracy_long=0.24,
        damage_vs_infantry=38.0,
        damage_vs_light_armor=10.0,
        damage_vs_heavy_armor=2.0,
        rpm=850,
        burst_size=15,
        suppress_power=0.52,
        ammo_capacity=250,
        year_introduced=1934,
        notes="Vehicle-mounted MG34, used on armored cars and half-tracks",
    )

    # --- Mills Bomb (British grenade) ---
    weapons["uk_mills_bomb"] = WeaponProfile(
        id="uk_mills_bomb",
        name="No.36 Mills Bomb",
        weapon_type=WeaponType.GRENADE,
        users=[Faction.BRITISH, Faction.POLISH],
        range_short=1,
        range_medium=2,
        range_long=0,
        range_max=2,
        accuracy_short=0.80,
        accuracy_medium=0.50,
        accuracy_long=0.0,
        damage_vs_infantry=45.0,
        damage_vs_light_armor=8.0,
        damage_vs_heavy_armor=1.0,
        rpm=6,
        burst_size=1,
        suppress_power=0.30,
        can_penetrate=False,
        area_effect=True,
        splash_radius=1,
        ammo_capacity=6,
        year_introduced=1915,
        notes="British fragmentation grenade, standard issue for infantry",
    )
    return weapons
